### PR TITLE
ipbus transport axi sim

### PR DESCRIPTION
**Pull request by alessandrothea**
This PR fixes the ipbus transport axi sim

### CODE REVIEW

**Comment by alessandrothea** [comment]
Run tests

**Review by tswilliams — DISMISSED** [review]

**Comment by alessandrothea** [comment]
Run tests please

**Comment by alessandrothea** [comment]
Run tests please

**Comment by alessandrothea** [comment]
Run tests please

**Review by tswilliams — APPROVED** [review]

**Pull request merged**
